### ISSUE TITLE
Infinite loading when I accept policy & terms is toggled, UI issues

### ISSUE THREAD

**Issue by rootedBotnet** [sustcast/sustcast-android-app-v1#28]
1. Just toggle _I accept policy & terms_ then click _Sign Up_. The progress bar will load infinitely. Expected behavior can be like disabling the button when policies are not agreed.

![InkedScreenshot_2020-10-06-01-41-12-637_com sust sustcast_LI](https://user-images.githubusercontent.com/72339844/95180367-b32d6780-07e3-11eb-957c-6f1104260630.jpg)

Also, look at the red marked area.

2. When we switch between _news reader_ & _stream_ fragment the logo shifts a bit. It's like 10 dp or so. Another thing is that, sometimes while switching between those fragments, if _pause_ button is pressed, music continues to play. 

3. Sometimes clicking on _Feedback_ gives **null**.

![Screenshot_2020-10-06-15-08-51-752_com google android gm_LI](https://user-images.githubusercontent.com/72339844/95182457-757e0e00-07e6-11eb-8e9e-d54901499e09.jpg)

**Comment by shuhanmirza** [comment]
@sustcast/tech-team please look into these.

**Comment by shuhanmirza** [comment]
@rootedBotnet you are using the latest app, right?

**Comment by rootedBotnet** [comment]
Yeah!  Latest version from Google play.

**Comment by istiakshihab** [comment]
Can you post your OS Name (with Version) and the Model of your Mobile? @rootedBotnet

**Comment by rootedBotnet** [comment]
@istiakshihab Sure.

OS: MIUI 12.0.1 Xiaomi EU (Custom ROM)
Android version: 10
Device name: Pocophone F1

I also had similar issues on another device of mine. It has the following specifications:

OS: MIUI 11.0.5 
Android version: 9
Device name: Redmi S2

**Comment by rootedBotnet** [comment]
# Shift of logo:
![ezgif-7-553de2231b4b](https://user-images.githubusercontent.com/72339844/95306382-24831e00-08a9-11eb-9f74-b5b886c08a10.gif)

**Comment by meafs** [comment]
All of these are fixed now. So, we should close the issue.

**Comment by appledora** [comment]
good job :D
