### ISSUE TITLE
UI improvements 

### ISSUE THREAD

**Issue by rootedBotnet** [sustcast/sustcast-android-app-v1#33]
Current UI of the application is superb & I think we can add these to the app:

1. https://github.com/fornewid/neumorphism
2. https://github.com/GrenderG/Toasty

**Comment by appledora** [comment]
Will look into it - but may not integrate until the next big update.

**Comment by appledora** [comment]
@meafs you can go ahead and add toasty, when other bugs are fixed. Neumorphism will be on pause for now.
